-- ============================================================
-- OLIST BRAZILIAN E-COMMERCE DATASET
-- SCHEMA DESIGN (DERIVED FROM KAGGLE RELATIONSHIP DIAGRAM)
-- https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce?select=olist_geolocation_dataset.csv

-- ============================================================

-- ----------------------------
-- TABLE: customers
-- Grain: one row per customer
-- Primary Key: customer_id
-- Notes:
-- - customer_unique_id groups multiple customer_id values
--   (same person can have multiple accounts)
-- ----------------------------
-- customers(
--   customer_id PK,
--   customer_unique_id,
--   customer_zip_code_prefix,
--   customer_city,
--   customer_state
-- )

-- ----------------------------
-- TABLE: orders
-- Grain: one row per order
-- Primary Key: order_id
-- Foreign Keys:
-- - customer_id -> customers.customer_id
-- Notes:
-- - not all orders have associated order_items (e.g. canceled)
-- ----------------------------
-- orders(
--   order_id PK,
--   customer_id FK,
--   order_status,
--   order_purchase_timestamp,
--   order_approved_at,
--   order_delivered_carrier_date,
--   order_delivered_customer_date,
--   order_estimated_delivery_date
-- )

-- ----------------------------
-- TABLE: order_items
-- Grain: one row per item within an order
-- Primary Key: (order_id, order_item_id) 
-- Foreign Keys:
-- - order_id -> orders.order_id
-- - product_id -> products.product_id
-- Notes:
-- - order_item_id is only unique within an order
-- - price and freight_value live at item grain
-- ----------------------------
-- order_items(
--   order_id PK/FK,
--   order_item_id PK,
--   product_id FK,
--   seller_id,
--   shipping_limit_date,
--   price,
--   freight_value
-- )

-- ----------------------------
-- TABLE: products
-- Grain: one row per product
-- Primary Key: product_id
-- Foreign Keys:
-- - product_category_name -> product_category_translation.product_category_name
-- Notes:
-- - product_category_name may be NULL
-- ----------------------------
-- products(
--   product_id PK,
--   product_category_name,
--   product_name_lenght,
--   product_description_lenght,
--   product_photos_qty
-- )

-- ----------------------------
-- TABLE: order_payments
-- Grain: one row per payment event for an order
-- Primary Key: (order_id, payment_sequential)
-- Foreign Keys:
-- - order_id -> orders.order_id
-- Notes:
-- - an order may have multiple payment records
-- ----------------------------
-- order_payments(
--   order_id PK/FK,
--   payment_sequential PK,
--   payment_type,
--   payment_installments,
--   payment_value
-- )

-- ----------------------------
-- OPTIONAL TABLES (LATER)
-- - order_reviews
-- - sellers
-- - geolocation
-- ----------------------------

-- ----------------------------
-- DATA LOAD ORDER (IMPORTANT)
-- 1. customers
-- 2. products
-- 3. orders
-- 4. order_items
-- 5. order_payments
-- ----------------------------

-- ----------------------------
-- DESIGN PRINCIPLES
-- - Foreign key constraints are used to explicitly enforce valid relationships between tables.
-- - Composite primary keys are defined where necessary to correctly reflect the real-world grain of each table.
-- - The schema is designed to support complex multi-table joins and aggregation-heavy analytical queries.
-- ----------------------------




-- -- Customers
-- CREATE TABLE customers (
--     customer_id VARCHAR PRIMARY KEY,
--     customer_unique_id VARCHAR,
--     customer_zip_code_prefix INT,
--     customer_city VARCHAR,
--     customer_state VARCHAR
-- );

-- -- Orders (hub table)
-- CREATE TABLE orders (
--     order_id VARCHAR PRIMARY KEY,
--     customer_id VARCHAR REFERENCES customers(customer_id),
--     order_status VARCHAR,
--     order_purchase_timestamp TIMESTAMP,
--     order_approved_at TIMESTAMP,
--     order_delivered_carrier_date TIMESTAMP,
--     order_delivered_customer_date TIMESTAMP,
--     order_estimated_delivery_date TIMESTAMP
-- );

-- -- Products
-- CREATE TABLE products (
--     product_id VARCHAR PRIMARY KEY,
--     product_category_name VARCHAR,
--     product_name_lenght INT,
--     product_description_lenght INT,
--     product_photos_qty INT
-- );

-- -- Order Items (many-to-one with orders)
-- CREATE TABLE order_items (
--     order_id VARCHAR REFERENCES orders(order_id),
--     order_item_id INT,
--     product_id VARCHAR REFERENCES products(product_id),
--     seller_id VARCHAR,
--     shipping_limit_date TIMESTAMP,
--     price NUMERIC,
--     freight_value NUMERIC,
--     PRIMARY KEY (order_id, order_item_id)
-- );

-- -- Payments
-- CREATE TABLE order_payments (
--     order_id VARCHAR REFERENCES orders(order_id),
--     payment_sequential INT,
--     payment_type VARCHAR,
--     payment_installments INT,
--     payment_value NUMERIC,
--     PRIMARY KEY (order_id, payment_sequential)
-- );
